### ISSUE TITLE
Create CycloneDX SBOM by default as a Jenkins Artifact

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2900]
Jenkins builds currently produce a CycloneDX SBOM printed in the Console output, when a BUILD_ARG of "--create-sbom" is specified.
Extended this to actually produce the json as a Jenkins artifact by default in all builds.

**Comment by sophia-guo** [comment]
@smlambert I can help this if you have other high priority jobs.

**Comment by smlambert** [comment]
@sophia-guo - that will be great!  I have assigned us both (as I want to stay close on this, but I think there will be several pieces and I know you will be able to progress it faster than I will, thanks for the offer!).

**Comment by smlambert** [comment]
FYI @sophia-guo that first step is in @zdtsw 's PR https://github.com/adoptium/ci-jenkins-pipelines/pull/296 enables the printing of SBOM to console 

@zdtsw - have you also put your name against SBOM work?  Here is one way it could be broken down and shared...

1. enable the commandline argument (via ci-jenkins-pipelines/pull/296)
2. make any necessary changes to have it create an actual json file in the event it just prints to console (code [here](https://github.com/adoptium/temurin-build/tree/master/cyclonedx-lib))
3. archive the file to the Jenkins job.  
4. can be done in tandem with the other steps is to ensure the contents of the SBOM are more complete (related: https://github.com/adoptium/temurin-build/issues/2813)
5. push the SBOM to the releases repository
6. update the API to be able to serve up the SBOM
7. additional enhancements to SBOM, such as, if latest version of cycloneDX available 1.5 will have a 'platform' type, if so, we should consider switching from using 'application' to 'platform' for Temurin

**Comment by zdtsw** [comment]
> FYI @sophia-guo that first step is in @zdtsw 's PR [adoptium/ci-jenkins-pipelines#296](https://github.com/adoptium/ci-jenkins-pipelines/pull/296) enables the printing of SBOM to console
> 
> @zdtsw - have you also put your name against SBOM work? Here is one way it could be broken down and shared...
> 
> 1. enable the commandline argument (via ci-jenkins-pipelines/pull/296)
> 2. make any necessary changes to have it create an actual json file in the event it just prints to console (code [here](https://github.com/adoptium/temurin-build/tree/master/cyclonedx-lib))
> 3. archive the file to the Jenkins job.
> 4. can be done in tandem with the other steps is to ensure the contents of the SBOM are more complete (related: [Determine exact Bill of Materials for building a single JDK linux library using strace #2813](https://github.com/adoptium/temurin-build/issues/2813))
> 5. push the SBOM to the releases repository
> 6. update the API to be able to serve up the SBOM
> 7. additional enhancements to SBOM, such as, if latest version of cycloneDX available 1.5 will have a 'platform' type, if so, we should consider switching from using 'application' to 'platform' for Temurin

@smlambert I actually changed my mind to move the "enabler" function into ci-jenkins-pipeline [PR](https://github.com/adoptium/ci-jenkins-pipelines/pull/296) which has a better switch on/off by different pipeline. 
this PR does cover 1) enable CLI with new flag and 2) calling cyclonedb jar but not directly to the jenkins artifact part and steps afterwards

**Comment by zdtsw** [comment]
Another question: 

could we de-couple the implementation of cyclonedb-lib into its own git repo?
so we can build different version and update cyclonedx-core-java to newer version (7.1.4 at the moment) without updates in this repo.
also we do not need to build it every time in pipeline esp. when it becomes a default behavior.

**Comment by smlambert** [comment]
re: https://github.com/adoptium/temurin-build/issues/2900#issuecomment-1124913775 as per discussion today, we will leave things in the temurin-build repo for now, as its only a handful of classes and compile time is nominal.  This can be revisited later as needed.

**Comment by zdtsw** [comment]
To make this issue easy to be split and assigned

- [:hourglass: ] enable the commandline argument (via ci-jenkins-pipelines/pull/296)

- [:hourglass:  ] make any necessary changes to have it create an actual json file in the event it just prints to console (code [here](https://github.com/adoptium/temurin-build/tree/master/cyclonedx-lib)) : same PR as above, verification work

- [ ] archive the file to the Jenkins job. can be done in tandem with the other steps is to ensure the contents of the SBOM are more complete (related: https://github.com/adoptium/temurin-build/issues/2813)

- [ ] push the SBOM to the releases repository

- [ ] update the API to be able to serve up the SBOM

- [ TODO]: additional enhancements to SBOM, such as, if latest version of cycloneDX available 1.5 will have a 'platform' type, if so, we should consider switching from using 'application' to 'platform' for Temurin

**Comment by zdtsw** [comment]
changed back to old solution to enable OS except windows and aix for the time being:
- https://github.com/adoptium/temurin-build/pull/2929 set default back to "false"
- https://github.com/adoptium/ci-jenkins-pipelines/pull/297 set extra buildArgs for OS*jdk

**Comment by zdtsw** [comment]
assume the new Type is **framework**, not **platform** ? if so, it has been updated. @smlambert 
`
11:43:45    "components" : [
11:43:45      {
11:43:45        "author" : "Vendor: Eclipse",
11:43:45        "group" : "Eclipse Temurin",
11:43:45        "name" : "Temurin",
11:43:45        "version" : "19-beta+24-202205300937",
11:43:45        "type" : "framework"
11:43:45      },
11:43:45      {
11:43:45        "name" : "JDK",
11:43:45        "description" : "Temurin JDK Component",
11:43:45        "properties" : [
11:43:45          {
11:43:45            "name" : "scmRef",
11:43:45            "value" : "1102dba08df"
11:43:45          },
11:43:45          {
11:43:45            "name" : "openjdkSourceCommit",
11:43:45            "value" : "https://github.com/adoptium/jdk/commit/1102dba08df"
11:43:45          },
11:43:45          {
11:43:45            "name" : "buildRef",
11:43:45            "value" : "https://github.com/adoptium/temurin-build/commit/dd97246"
11:43:45          },
11:43:45          {
11:43:45            "name" : "builtConfig",
...
`
