### ISSUE TITLE
Update reproducible comparing tests on linux (not docker image)

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#3687]
Part of https://github.com/adoptium/temurin-build/issues/3683

- [x] SCM_REF build issue https://github.com/adoptium/temurin-build/issues/3710
- [x] sbom with personal build branch and sha
- [x] Retrieving boot JDK 21.0.2+13-LTS not available -- BOOTJDK version is not abvailable by API https://ci.adoptium.net/view/Test_grinder/job/Grinder/9300/ -- remove suffix -LTS if bootjdk include -LTS
- [x] error: pathspec '"e95140bf52915bda6c5ff271538789ed9a55162b\ne95140bf52915bda6c5ff271538789ed9a55162b\ne95140bf52915bda6c5ff271538789ed9a55162b\ne95140bf52915bda6c5ff271538789ed9a55162b\ne95140bf52915bda6c5ff271538789ed9a55162b"' did not match any file(s) known to git. https://github.com/adoptium/temurin-build/issues/3687#issuecomment-2018898703
- [ ] Support running with upsteam jenkins jobs by mount test resources hit the user permission issue https://github.com/adoptium/infrastructure/issues/3490

**Comment by sophia-guo** [comment]
Trying in adopitum jenkins with some necessary updates. 
On [test-ibmcloud-rhel7-x64-1](https://ci.adoptium.net/computer/test-ibmcloud-rhel7-x64-1) https://ci.adoptium.net/view/Test_system/job/Test_openjdk21_hs_dev.system_x86-64_linux/21/console

```
15:19:17  TESTING:
15:19:18  Loaded plugins: product-id, search-disabled-repos, subscription-manager
15:19:18  You need to be root to perform this command.
```
That is in linux_repro_build_compare.sh if it's rhel that some extra tools are needed to install https://github.com/adoptium/temurin-build/blob/master/tooling/reproducible/linux_repro_build_compare.sh#L27-L37. However jenkins doesn't have the permission.

**Comment by sophia-guo** [comment]
For non-rhel for now jq is need to install, which also has the permission issue. Can we ask the infra to install `jq`, which is also required for windows. @andrew-m-leonard @sxa

**Comment by sophia-guo** [comment]
SCM_REF build issue https://github.com/adoptium/temurin-build/issues/3710

**Comment by sophia-guo** [comment]
Upstream build is triggered by personal temrurin-build ( could be the old repo openjdk-build) branch and sha, which will cause build failed -

       {
          "name" : "Temurin Build Ref",
          "value" : "https://github.com/andrew-m-leonard/openjdk-build/commit/532e5d1f4c39c121b42303c8f29d69e007ce96fe"
        },

```
15:32:44  Cloning into 'temurin-build'...
15:32:45  error: pathspec '"532e5d1f4c39c121b42303c8f29d69e007ce96fe\n532e5d1f4c39c121b42303c8f29d69e007ce96fe\n532e5d1f4c39c121b42303c8f29d69e007ce96fe\n532e5d1f4c39c121b42303c8f29d69e007ce96fe\n532e5d1f4c39c121b42303c8f29d69e007ce96fe"' did not match any file(s) known to git.
```

**Comment by sophia-guo** [comment]
@andrew-m-leonard see https://github.com/adoptium/temurin-build/issues/3687#issuecomment-2015862778

**Comment by sophia-guo** [comment]
> https://github.com/adoptium/temurin-build/issues/3687#issuecomment-2015862778

This happened if `Temurin Build Ref` is referred my develper's personal repo.

However I've tried the release version with main repo got the similar issue. - Using release jdk22 linux-x64 https://ci.adoptium.net/job/build-scripts/job/release-openjdk22-pipeline/5/artifact/target/linux/x64/temurin/OpenJDK22U-sbom_x64_linux_hotspot_22_36.json/*view*/ I got similar error 

```
16:36:01  error: pathspec '"e95140bf52915bda6c5ff271538789ed9a55162b\ne95140bf52915bda6c5ff271538789ed9a55162b\ne95140bf52915bda6c5ff271538789ed9a55162b\ne95140bf52915bda6c5ff271538789ed9a55162b\ne95140bf52915bda6c5ff271538789ed9a55162b"' did not match any file(s) known to git.
16:36:02  reproducibleCompare

```

https://ci.adoptium.net/view/Test_grinder/job/Grinder/9302/consoleFull

**Comment by sophia-guo** [comment]
e95140bf52915bda6c5ff271538789ed9a55162b is the commit of branch https://github.com/adoptium/temurin-build/commits/v2024.03.01 , which is not in the master. Hence can't be found. Suppose reproducible comparing should support the release? @andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
> [e95140b](https://github.com/adoptium/temurin-build/commit/e95140bf52915bda6c5ff271538789ed9a55162b) is the commit of branch https://github.com/adoptium/temurin-build/commits/v2024.03.01 , which is not in the master. Hence can't be found. Suppose reproducible comparing should support the release? @andrew-m-leonard

Should it matter where the commitSHA is from ?

**Comment by sophia-guo** [comment]
Yes, according to the test 
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9302/consoleFull

**Comment by andrew-m-leonard** [comment]
I suspect this needs changing to not assume a git "branch" ? https://github.com/sophia-guo/openjdk-build/blob/33e187ebdab191756b3f6584ef3a24862e529d4c/test/system/reproducibleCompare/build.xml#L61
probably needs to clone, then do a checkout by SHA

**Comment by sophia-guo** [comment]
The build.xml only pre stages all shell scripts. https://github.com/sophia-guo/openjdk-build/blob/33e187ebdab191756b3f6584ef3a24862e529d4c/test/system/reproducibleCompare/build.xml#L61. 
The reproducible build params are coming from sbom.json file. 

The issue can be easily reproduced with master branch by following command

```
docker run -v "$(TEST_RESROOT):/home/jenkins/test" -w "/home/jenkins/test" --name reproducibleCompare centos:7 /bin/bash /home/jenkins/test/linux_repro_build_compare.sh  /home/jenkins/jdkbinary/OpenJDK22U-sbom_x64_linux_hotspot_22_36.json /home/jenkins/jdkbinary/OpenJDK22U-jdk_x64_linux_hotspot_22_36.tar.gz
```
export $(TEST_RESROOT) to local temurin-build/tooling/reproducible. Download the jdkfile and sbom file to same directory. Update linux_repro_build_compare.sh to support local files.

**Comment by andrew-m-leonard** [comment]
@sophia-guo The jq command needs fixing, the git checkout command it is running is:
```
(cd temurin-build && git checkout e95140bf52915bda6c5ff271538789ed9a55162b e95140bf52915bda6c5ff271538789ed9a55162b e95140bf52915bda6c5ff271538789ed9a55162b e95140bf52915bda6c5ff271538789ed9a55162b e95140bf52915bda6c5ff271538789ed9a55162b)
```
because jq is returning:
```
andrew@andrew:~/temurin-build/tooling/reproducible$ jq -r '.components[] | .properties[] | select (.name == "Temurin Build Ref") | .value' "OpenJDK22U-sbom_x64_linux_hotspot_22_36.json" | awk -F/ '{print $NF}'
e95140bf52915bda6c5ff271538789ed9a55162b
e95140bf52915bda6c5ff271538789ed9a55162b
e95140bf52915bda6c5ff271538789ed9a55162b
e95140bf52915bda6c5ff271538789ed9a55162b
e95140bf52915bda6c5ff271538789ed9a55162b
```

**Comment by sophia-guo** [comment]
> https://github.com/adoptium/temurin-build/issues/3687#issuecomment-2022959975

I see. Seems SBOM file content changed.  For this specific sbomfile there are 4 components ( jdk, jre, static-lib, debug). All properties of those 4 components are duplicate except filename itself.

**Comment by sophia-guo** [comment]
The diff for reproducing release jdk22 is as following 

```
diff -r jdk-22+36/release compare.1/jdk-22+36/release
11,13d10
< BUILD_SOURCE="git:e95140bf52915bda6c5ff271538789ed9a55162b"
< BUILD_SOURCE_REPO="https://github.com/adoptium/temurin-build.git"
< SOURCE_REPO="https://github.com/adoptium/jdk22.git"
```

That is for reproducing one the release file doesn't have those information, which is minor but not sure if it is expected. @andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
> The diff for reproducing release jdk22 is as following
> 
> ```
> diff -r jdk-22+36/release compare.1/jdk-22+36/release
> 11,13d10
> < BUILD_SOURCE="git:e95140bf52915bda6c5ff271538789ed9a55162b"
> < BUILD_SOURCE_REPO="https://github.com/adoptium/temurin-build.git"
> < SOURCE_REPO="https://github.com/adoptium/jdk22.git"
> ```
> 
> That is for reproducing one the release file doesn't have those information, which is minor but not sure if it is expected. @andrew-m-leonard

I thought that should be clean'd by this https://github.com/adoptium/temurin-build/blob/646a79f2668378151985bc9517392ad955555ea6/tooling/reproducible/repro_common.sh#L349

**Comment by sophia-guo** [comment]
Linux_repro_build_compare.sh doesn't use the repro_common.sh

**Comment by andrew-m-leonard** [comment]
> Linux_repro_build_compare.sh doesn't use the repro_common.sh

Ah yes, so we should re-use that clean method to make these compare if possible?

**Comment by sophia-guo** [comment]
We can do in separate issue or pr later.
