### ISSUE TITLE
EPIC: Provide the ability for 3rd party Temurin release reproducible Attestation

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3948]
The idea of "Attestation" of Trusted Reproducible Verification ties into the secure development and secure supply chain verification, and strengthens the Adoptium SLSA levels.

This epic describes the tasks required to provide a means for Eclipse Temurin release to be "Attested" to a 3rd party completing a secure Trusted Reproducible Verification build.

- [ ] Create a documented outline of the 3rd party Reproducible Attestation process
- [ ] Architect a "Reproducible Build Attestation"
- [ ] Design and build a "Reproducible Build Attestation" and it's Adoptium "process"
- [ ]
